import m5

def addSPOptions(parser):
    parser.add_option("--disable-rgdb", action="store_true", help="disable the listening to \
                        remote gdb for preventing disturb")
    parser.add_option("--disable-vnc", action="store_true", help="disable the listening to \
                        vnc for preventing disturb")
    parser.add_option("--sp-trace", action="store_true",
                        help="dump trace for selected interval")
    parser.add_option("--sp-skip-trace", type="int", default=0,
                        help="don't dump trace until this number of instructions simulated")
    parser.add_option("--simpoint-bbv-file", type="str", default=None,
                        help="the bbv file generated by simpoint probe")
